# Generated by Django 6.1.1 on 2026-09-24 18:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(blank=True, max_length=150)),
                ('headline', models.CharField(blank=True, max_length=255)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('linkedin_url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('portfolio_url', models.URLField(blank=True)),
                ('profile_photo_url', models.URLField(blank=True)),
                ('additional_info', models.TextField(blank=True)),
                ('header_completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'students',
            },
        ),
        migrations.CreateModel(
            name='StudentCertification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('certification', 'Certification'), ('award', 'Award')], default='certification', max_length=15)),
                ('title', models.CharField(max_length=255)),
                ('issuer', models.CharField(blank=True, max_length=200)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('credential_url', models.URLField(blank=True)),
                ('badge_url', models.URLField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='students.student')),
            ],
            options={
                'db_table': 'student_certifications',
                'ordering': ['student', 'type', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='StudentEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('degree', models.CharField(max_length=150)),
                ('specialization', models.CharField(blank=True, max_length=150)),
                ('institution', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=150)),
                ('passing_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('score', models.CharField(blank=True, max_length=20)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='students.student')),
            ],
            options={
                'db_table': 'student_education',
                'ordering': ['student', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='StudentExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_name', models.CharField(max_length=200)),
                ('job_title', models.CharField(max_length=150)),
                ('location', models.CharField(blank=True, max_length=150)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='students.student')),
            ],
            options={
                'db_table': 'student_experiences',
                'ordering': ['student', 'sort_order', '-start_date'],
            },
        ),
        migrations.CreateModel(
            name='StudentProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_name', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('selected', 'Selected'), ('in_progress', 'In progress'), ('completed', 'Completed')], default='selected', max_length=15)),
                ('github_link', models.URLField(blank=True)),
                ('live_link', models.URLField(blank=True)),
                ('custom_notes', models.TextField(blank=True)),
                ('show_on_resume', models.BooleanField(default=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('experience', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='students.studentexperience')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_selections', to='catalog.courseproject')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_selections', to='students.student')),
            ],
            options={
                'db_table': 'student_projects',
            },
        ),
        migrations.CreateModel(
            name='StudentSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='catalog.course')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary_selection', to='students.student')),
                ('summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_selections', to='catalog.coursesummary')),
            ],
            options={
                'verbose_name_plural': 'student summaries',
                'db_table': 'student_summaries',
            },
        ),
        migrations.CreateModel(
            name='StudentCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('enrolled', 'Enrolled'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('dropped', 'Dropped')], default='enrolled', max_length=15)),
                ('show_on_resume', models.BooleanField(default=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_selections', to='catalog.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_selections', to='students.student')),
            ],
            options={
                'db_table': 'student_courses',
                'constraints': [models.UniqueConstraint(fields=('student', 'course'), name='uniq_student_course')],
            },
        ),
        migrations.AddConstraint(
            model_name='studentexperience',
            constraint=models.CheckConstraint(condition=models.Q(('is_current', True), ('end_date__isnull', False), _connector='OR'), name='experience_end_date_required'),
        ),
        migrations.AddConstraint(
            model_name='studentexperience',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='experience_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='studentproject',
            constraint=models.UniqueConstraint(fields=('student', 'project'), name='uniq_student_project'),
        ),
    ]
