# Generated by Django 6.1.1 on 2026-09-29 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_remove_course_is_published_and_more'),
        ('students', '0002_remove_student_profile_photo_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_selections', to='students.student')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_selections', to='catalog.coursetopic')),
            ],
            options={
                'db_table': 'student_topics',
                'constraints': [models.UniqueConstraint(fields=('student', 'topic'), name='uniq_student_topic')],
            },
        ),
    ]
