# Generated by Django 6.1.1 on 2026-09-30 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_remove_course_is_published_and_more'),
        ('students', '0003_studenttopic'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentTopicContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_selections', to='catalog.topiccontent')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_selections', to='students.student')),
            ],
            options={
                'db_table': 'student_topic_contents',
                'constraints': [models.UniqueConstraint(fields=('student', 'content'), name='uniq_student_content')],
            },
        ),
    ]
