# Generated by Django 6.1.1 on 2026-09-28 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='courseproject',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='courseproject',
            name='thumbnail_url',
        ),
        migrations.RemoveField(
            model_name='coursetopic',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='topiccontent',
            name='duration_minutes',
        ),
        migrations.RemoveField(
            model_name='topiccontent',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='topiccontent',
            name='media_url',
        ),
        migrations.AlterField(
            model_name='projectcontent',
            name='content_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image')], default='text', max_length=10),
        ),
        migrations.AlterField(
            model_name='topiccontent',
            name='content_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image')], default='text', max_length=10),
        ),
    ]
